### ISSUE TITLE
EKS cluster bootstrap

### ISSUE THREAD

**Issue by iliazlobin** [cloudposse/terraform-aws-components#325]
## Describe the Bug

Bootstrapping the EKS cluster doesn't seem to be worked out. There are a few self-references on the deployed component. But how would you deploy the component with self-references without yet having one? Where data sources are going to pull information from?

## Expected Behavior

When putting out an atmos stack definition for an EKS component without any code modification and launching a stack deploy command the first time, I expect it to set up an AWS EKS cluster without errors and complaints.

## Steps to Reproduce

The code is taken from the following sources:
* [latest terraform componenets](https://github.com/cloudposse/terraform-aws-components/tree/all-new-components/modules)
* [atmos stack config](https://github.com/cloudposse/atmos)

Put out and deploy fundamental atmos stacks - everything on a diagram except the EKS component:

![image](https://user-images.githubusercontent.com/3456942/119444369-2ae0e000-bd3c-11eb-8f33-219acaa4e438.png)

Define an EKS stack:
```
    eks:
      vars:
        aws_assume_role_arn: "arn:aws:iam::314028178888:role/atmos-gbl-test-terraform" # identity role for module
        tfstate_existing_role_arn: "arn:aws:iam::101236733906:role/atmos-gbl-root-terraform"
        cluster_kubernetes_version: "1.19"
        region_availability_zones: ["us-east-1b", "us-east-1c", "us-east-1d"]
        public_access_cidrs: ["72.107.0.0/24"]
        managed_node_groups_enabled: true
```

Run command to deploy a stack:
```
atmos terraform plan eks -s gbl-test
```

It'll end up triggering errors signifying about missing remote state of [the following components](https://github.com/cloudposse/terraform-aws-components/blob/all-new-components/modules/eks/remote-state.tf#L34-L61):
* workers_role
* eks

Commenting out the pieces of code and related variables/locals seems like resolving the issue, but it adds up so much of an overhead on bootstrapping the component. Imagine how hard it'd be to replicate the deployment onto other dozens of environments.
