### ISSUE TITLE
Bastion: An argument named "tags" is not expected here

### ISSUE THREAD

**Issue by johncblandii** [cloudposse/terraform-aws-components#743]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help.

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug

```bash
│ Error: Unsupported argument
│ 
│   on .terraform/modules/bastion_autoscale_group/main.tf line 244, in resource "aws_autoscaling_group" "default":
│  244:   tags = flatten([
│ 
│ An argument named "tags" is not expected here.
```

## Expected Behavior

Version 1.237.0 failures on a basic run that passes before 1.237.0, but that run will probably fail now as it seems to be the autoscale module that has the problem.

```yaml
components:
  terraform:
    bastion:
      vars:
        enabled: true
        name: bastion
        instance_type: t3.micro
        inbound_ssh_enabled: true
        associate_public_ip_address: true # deploy to public subnet and associate public IP with instance
        security_group_rules: []
```

## Steps to Reproduce

1. Create a bastion server using the values above
2. See error

## Screenshots

N/A

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: any
 - Version: any
