### ISSUE TITLE
ecs-service: circuit breaker params are ignored

### ISSUE THREAD

**Issue by johncblandii** [cloudposse/terraform-aws-components#931]
### Describe the Bug

https://github.com/cloudposse/terraform-aws-components/blob/main/modules/ecs-service/main.tf#L259

`deployment_controller_type         = lookup(local.task, "deployment_controller_type", null)` ends up passing in `null` which does not default to `ECS` for this conditional https://github.com/cloudposse/terraform-aws-ecs-alb-service-task/blob/main/main.tf#L642 so `circuit_breaker_deployment_enabled` and `circuit_breaker_rollback_enabled` never get enabled.

### Expected Behavior

```yaml
...
        task:
          circuit_breaker_deployment_enabled: true
          circuit_breaker_rollback_enabled: true
```

...should trigger...

```hcl
      ~ deployment_circuit_breaker {
          ~ enable   = false -> true
          ~ rollback = false -> true
        }
```

Changing the values should trigger an update, but it requires manually setting `deployment_controller_type: ECS`.

### Steps to Reproduce

Enable the circuit breaker for a task without explicitly setting the deployment controller.
